### ISSUE TITLE
「评论」友情链接

### ISSUE THREAD

**Issue by xiaoyu-666** [xiaoyu-666/xiaoyu-666.github.io#14]
友情链接：https://xiaoyu-666.github.io/friends/

**Comment by xiaoyu-666** [comment]
```yaml
- name: 小鱼博客 # 昵称
  desc: 积跬步以至千里，喜欢学习喜欢你。 # 介绍
  avatar: https://cdn.jsdelivr.net/gh/xugaoyi/image_store/blog/20200103123203.jpg # 头像
  link: https://xiaoyu-666.github.io/
```
